name: Add User to Organization

on:
  issues:
    types: [opened]

jobs:
  add-user:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'Request Membership' # Ensure it matches the issue template title
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Invite User to Organization
        env:
          ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          ISSUE_BODY=$(jq -r '.issue.body' < $GITHUB_EVENT_PATH)
          USERNAME=$(echo "$ISSUE_BODY" | sed -n 's/^@\(.*\)/\1/p')
          
          if [[ -n "$USERNAME" && "$USERNAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            echo "Sending invitation to $USERNAME..."
            
            curl -v -X PUT \
              -H "Authorization: token $ORG_ADMIN_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/orgs/GI-Low/memberships/$USERNAME
              
            ISSUE_NUMBER=$(jq -r '.issue.number' < $GITHUB_EVENT_PATH)
            
            curl -v -X PATCH \
              -H "Authorization: token $ORG_ADMIN_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"state":"closed"}' \
              https://api.github.com/repos/GI-Low/Membership/issues/$ISSUE_NUMBER
          else
            echo "Invalid or no username found in the issue body."
            exit 1
          fi
